# conda env create -f minimal_environment.yml
name: desihigh
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - wget 
  - numpy
  - matplotlib
  - pandas
  - astropy
  - scipy
  - fitsio
  - jupyter
  - pyephem
  - notebook>=6.1.5
  - nbformat >=5.0.2
